// flow-typed signature: 6f82a591be3b88658a2a72db4fc88a34
// flow-typed version: <<STUB>>/JSON_v~1.0.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'JSON'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'JSON' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'JSON/json2' {
  declare module.exports: any;
}

// Filename aliases
declare module 'JSON/json2.js' {
  declare module.exports: $Exports<'JSON/json2'>;
}
